name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.87.0
        with:
          targets: ${{ matrix.target }}

      - name: Install cross
        run: cargo install cross

      - name: Build
        run: cd fr && cross build --release --target ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.target }}
          path: fr/target/${{ matrix.target }}/release/fr

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.87.0
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cd fr && cargo build --release --target ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.target }}
          path: fr/target/${{ matrix.target }}/release/fr

  release:
    needs: [build-linux, build-macos]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Rename artifacts
        run: |
          mv artifacts/release-x86_64-unknown-linux-gnu/fr fr-${{ github.ref_name }}-x86_64-unknown-linux-gnu
          mv artifacts/release-aarch64-unknown-linux-gnu/fr fr-${{ github.ref_name }}-aarch64-unknown-linux-gnu
          mv artifacts/release-x86_64-apple-darwin/fr fr-${{ github.ref_name }}-x86_64-apple-darwin
          mv artifacts/release-aarch64-apple-darwin/fr fr-${{ github.ref_name }}-aarch64-apple-darwin

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            fr-${{ github.ref_name }}-x86_64-unknown-linux-gnu
            fr-${{ github.ref_name }}-aarch64-unknown-linux-gnu
            fr-${{ github.ref_name }}-x86_64-apple-darwin
            fr-${{ github.ref_name }}-aarch64-apple-darwin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}